@startuml JerichoDeployemnt

actor Browser

folder DockerHost {

    node ICNDB [
    ICNDB
    ===
    Vert.X App
    ---
    JVM
    ]

    database PostgreSQL [
        PostgreSQL DB
        ---
        Jokes
    ]

    node Jericho [
    Jericho
    ===
    Jericho-Attacker (Gattling)
    ---
    Jericho-Reporter (Gattling)
    ---
    Report-Viewer (Nginx)
    ]

}

ICNDB --> PostgreSQL: Data access layer
Jericho --> ICNDB: Stress test
Browser --> Jericho: Display report

@enduml